# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'hullplot_customer_data' so R CMD check does not flag undocumented data.
#' hullplot_customer_data: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 10 variables:
#' \describe{
#'   \item{customer_id}{character variable}
#'   \item{segment}{factor variable}
#'   \item{annual_spending}{numeric variable}
#'   \item{purchase_frequency}{numeric variable}
#'   \item{age}{numeric variable}
#'   \item{satisfaction}{numeric variable}
#'   \item{loyalty_member}{factor variable}
#'   \item{region}{factor variable}
#'   \item{channel}{factor variable}
#'   \item{preferred_category}{factor variable}
#' }
#' @keywords datasets internal
"hullplot_customer_data"

