# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'hullplot_quality_data' so R CMD check does not flag undocumented data.
#' hullplot_quality_data: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 300 rows and 12 variables:
#' \describe{
#'   \item{product_id}{character variable}
#'   \item{quality_group}{factor variable}
#'   \item{dimensional_accuracy}{numeric variable}
#'   \item{surface_finish}{numeric variable}
#'   \item{production_line}{factor variable}
#'   \item{shift}{factor variable}
#'   \item{operator}{factor variable}
#'   \item{temperature}{numeric variable}
#'   \item{pressure}{numeric variable}
#'   \item{material_grade}{factor variable}
#'   \item{defect_count}{integer variable}
#'   \item{production_cost}{numeric variable}
#' }
#' @keywords datasets internal
"hullplot_quality_data"

