# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'groupsummary_financial_data' so R CMD check does not flag undocumented data.
#' groupsummary_financial_data: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 9 variables:
#' \describe{
#'   \item{transaction_time}{POSIXct/POSIXt variable}
#'   \item{market_sector}{factor variable}
#'   \item{transaction_type}{factor variable}
#'   \item{risk_level}{ordered/factor variable}
#'   \item{transaction_amount}{numeric variable}
#'   \item{price_change_percent}{numeric variable}
#'   \item{volume_traded}{numeric variable}
#'   \item{volatility_index}{numeric variable}
#'   \item{portfolio_value}{numeric variable}
#' }
#' @keywords datasets internal
"groupsummary_financial_data"

