# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'hullplot_experimental_data' so R CMD check does not flag undocumented data.
#' hullplot_experimental_data: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 350 rows and 11 variables:
#' \describe{
#'   \item{experiment_id}{character variable}
#'   \item{condition}{factor variable}
#'   \item{response_x}{numeric variable}
#'   \item{response_y}{numeric variable}
#'   \item{batch}{factor variable}
#'   \item{timepoint}{factor variable}
#'   \item{replicate}{integer variable}
#'   \item{quality_score}{numeric variable}
#'   \item{dose_level}{numeric variable}
#'   \item{technician}{factor variable}
#'   \item{confidence}{numeric variable}
#' }
#' @keywords datasets internal
"hullplot_experimental_data"

