# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'categorical_quality_data' so R CMD check does not flag undocumented data.
#' categorical_quality_data: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 300 rows and 10 variables:
#' \describe{
#'   \item{patient_id}{character variable}
#'   \item{age}{numeric variable}
#'   \item{balanced_category}{factor variable}
#'   \item{moderately_imbalanced}{factor variable}
#'   \item{severely_imbalanced}{factor variable}
#'   \item{category_with_missing}{factor variable}
#'   \item{high_cardinality}{factor variable}
#'   \item{extreme_binary}{factor variable}
#'   \item{ordinal_scale}{ordered/factor variable}
#'   \item{inconsistent_entry}{factor variable}
#' }
#' @keywords datasets internal
"categorical_quality_data"

