# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'hullplot_clinical_data' so R CMD check does not flag undocumented data.
#' hullplot_clinical_data: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 400 rows and 11 variables:
#' \describe{
#'   \item{patient_id}{character variable}
#'   \item{disease_subtype}{factor variable}
#'   \item{biomarker_x}{numeric variable}
#'   \item{biomarker_y}{numeric variable}
#'   \item{age}{numeric variable}
#'   \item{gender}{factor variable}
#'   \item{severity_score}{numeric variable}
#'   \item{treatment_response}{factor variable}
#'   \item{hospital}{factor variable}
#'   \item{months_since_diagnosis}{numeric variable}
#'   \item{comorbidities}{integer variable}
#' }
#' @keywords datasets internal
"hullplot_clinical_data"

