# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'groupsummary_simple' so R CMD check does not flag undocumented data.
#' groupsummary_simple: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 100 rows and 5 variables:
#' \describe{
#'   \item{category}{factor variable}
#'   \item{group}{factor variable}
#'   \item{value1}{numeric variable}
#'   \item{value2}{numeric variable}
#'   \item{count_var}{integer variable}
#' }
#' @keywords datasets internal
"groupsummary_simple"

