# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'hullplot_survey_data' so R CMD check does not flag undocumented data.
#' hullplot_survey_data: example dataset for the jjstatsplot module
#'
#' Example dataset distributed with the jjstatsplot jamovi module for demonstration and testing.
#'
#' @format A data frame with 450 rows and 11 variables:
#' \describe{
#'   \item{respondent_id}{character variable}
#'   \item{political_orientation}{factor variable}
#'   \item{economic_conservatism}{numeric variable}
#'   \item{social_conservatism}{numeric variable}
#'   \item{age}{numeric variable}
#'   \item{education}{factor variable}
#'   \item{income_level}{factor variable}
#'   \item{region}{factor variable}
#'   \item{voter_turnout}{factor variable}
#'   \item{news_source}{factor variable}
#'   \item{institutional_trust}{numeric variable}
#' }
#' @keywords datasets internal
"hullplot_survey_data"

