
# This file is automatically generated, you probably don't want to edit this

jjbarstatsOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jjbarstatsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            grvar = NULL,
            counts = NULL,
            excl = TRUE, ...) {

            super$initialize(
                package='jjstatsplot',
                name='jjbarstats',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..grvar <- jmvcore::OptionVariable$new(
                "grvar",
                grvar,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..excl <- jmvcore::OptionBool$new(
                "excl",
                excl,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..grvar)
            self$.addOption(private$..counts)
            self$.addOption(private$..excl)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        grvar = function() private$..grvar$value,
        counts = function() private$..counts$value,
        excl = function() private$..excl$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..grvar = NA,
        ..counts = NA,
        ..excl = NA)
)

jjbarstatsResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bar Charts",
                refs=list(
                    "ggplot2",
                    "ggstatsplot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do",
                clearWith=list(
                    "dep",
                    "group",
                    "grvar",
                    "direction")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Bar Chart",
                width=800,
                height=600,
                renderFun=".plot",
                requiresData=TRUE,
                clearWith=list(
                    "dep",
                    "group",
                    "grvar",
                    "direction")))}))

jjbarstatsBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jjbarstatsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jjstatsplot',
                name = 'jjbarstats',
                version = c(1,0,0),
                options = options,
                results = jjbarstatsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Bar Charts
#'
#' 'Wrapper Function for ggstatsplot::ggbarstats and
#' ggstatsplot::grouped_ggbarstats to generate Bar Charts.'
#' 
#'
#' @examples
#' \dontrun{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param dep .
#' @param group .
#' @param grvar .
#' @param counts .
#' @param excl .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jjbarstats <- function(
    data,
    dep,
    group,
    grvar,
    counts,
    excl = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('jjbarstats requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(grvar)) grvar <- jmvcore::resolveQuo(jmvcore::enquo(grvar))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(grvar), grvar, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in grvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jjbarstatsOptions$new(
        dep = dep,
        group = group,
        grvar = grvar,
        counts = counts,
        excl = excl)

    analysis <- jjbarstatsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
