
# This file is automatically generated, you probably don't want to edit this

jjhistostatsOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jjhistostatsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            grvar = NULL,
            excl = TRUE,
            typestatistics = "parametric",
            centralityparameter = "mean",
            changebinwidth = FALSE,
            binwidth = 1.1,
            barmeasure = "count",
            usexlab = FALSE,
            xlab = "",
            useylab = FALSE,
            ylab = "",
            usetitle = FALSE,
            title = "",
            usesubtitle = FALSE,
            subtitle = "",
            useplotcaption = FALSE,
            plotcaption = "",
            resultssubtitle = TRUE,
            originaltheme = FALSE, ...) {

            super$initialize(
                package='jjstatsplot',
                name='jjhistostats',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..grvar <- jmvcore::OptionVariable$new(
                "grvar",
                grvar,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..excl <- jmvcore::OptionBool$new(
                "excl",
                excl,
                default=TRUE)
            private$..typestatistics <- jmvcore::OptionList$new(
                "typestatistics",
                typestatistics,
                options=list(
                    "parametric",
                    "robust",
                    "bayes"),
                default="parametric")
            private$..centralityparameter <- jmvcore::OptionList$new(
                "centralityparameter",
                centralityparameter,
                options=list(
                    "mean",
                    "median",
                    "none"),
                default="mean")
            private$..changebinwidth <- jmvcore::OptionBool$new(
                "changebinwidth",
                changebinwidth,
                default=FALSE)
            private$..binwidth <- jmvcore::OptionNumber$new(
                "binwidth",
                binwidth,
                default=1.1)
            private$..barmeasure <- jmvcore::OptionList$new(
                "barmeasure",
                barmeasure,
                options=list(
                    "count",
                    "density",
                    "proportion",
                    "mix"),
                default="count")
            private$..usexlab <- jmvcore::OptionBool$new(
                "usexlab",
                usexlab,
                default=FALSE)
            private$..xlab <- jmvcore::OptionString$new(
                "xlab",
                xlab,
                default="")
            private$..useylab <- jmvcore::OptionBool$new(
                "useylab",
                useylab,
                default=FALSE)
            private$..ylab <- jmvcore::OptionString$new(
                "ylab",
                ylab,
                default="")
            private$..usetitle <- jmvcore::OptionBool$new(
                "usetitle",
                usetitle,
                default=FALSE)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..usesubtitle <- jmvcore::OptionBool$new(
                "usesubtitle",
                usesubtitle,
                default=FALSE)
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..useplotcaption <- jmvcore::OptionBool$new(
                "useplotcaption",
                useplotcaption,
                default=FALSE)
            private$..plotcaption <- jmvcore::OptionString$new(
                "plotcaption",
                plotcaption,
                default="")
            private$..resultssubtitle <- jmvcore::OptionBool$new(
                "resultssubtitle",
                resultssubtitle,
                default=TRUE)
            private$..originaltheme <- jmvcore::OptionBool$new(
                "originaltheme",
                originaltheme,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..grvar)
            self$.addOption(private$..excl)
            self$.addOption(private$..typestatistics)
            self$.addOption(private$..centralityparameter)
            self$.addOption(private$..changebinwidth)
            self$.addOption(private$..binwidth)
            self$.addOption(private$..barmeasure)
            self$.addOption(private$..usexlab)
            self$.addOption(private$..xlab)
            self$.addOption(private$..useylab)
            self$.addOption(private$..ylab)
            self$.addOption(private$..usetitle)
            self$.addOption(private$..title)
            self$.addOption(private$..usesubtitle)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..useplotcaption)
            self$.addOption(private$..plotcaption)
            self$.addOption(private$..resultssubtitle)
            self$.addOption(private$..originaltheme)
        }),
    active = list(
        dep = function() private$..dep$value,
        grvar = function() private$..grvar$value,
        excl = function() private$..excl$value,
        typestatistics = function() private$..typestatistics$value,
        centralityparameter = function() private$..centralityparameter$value,
        changebinwidth = function() private$..changebinwidth$value,
        binwidth = function() private$..binwidth$value,
        barmeasure = function() private$..barmeasure$value,
        usexlab = function() private$..usexlab$value,
        xlab = function() private$..xlab$value,
        useylab = function() private$..useylab$value,
        ylab = function() private$..ylab$value,
        usetitle = function() private$..usetitle$value,
        title = function() private$..title$value,
        usesubtitle = function() private$..usesubtitle$value,
        subtitle = function() private$..subtitle$value,
        useplotcaption = function() private$..useplotcaption$value,
        plotcaption = function() private$..plotcaption$value,
        resultssubtitle = function() private$..resultssubtitle$value,
        originaltheme = function() private$..originaltheme$value),
    private = list(
        ..dep = NA,
        ..grvar = NA,
        ..excl = NA,
        ..typestatistics = NA,
        ..centralityparameter = NA,
        ..changebinwidth = NA,
        ..binwidth = NA,
        ..barmeasure = NA,
        ..usexlab = NA,
        ..xlab = NA,
        ..useylab = NA,
        ..ylab = NA,
        ..usetitle = NA,
        ..title = NA,
        ..usesubtitle = NA,
        ..subtitle = NA,
        ..useplotcaption = NA,
        ..plotcaption = NA,
        ..resultssubtitle = NA,
        ..originaltheme = NA)
)

jjhistostatsResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        plot2 = function() private$.items[["plot2"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Histogram",
                refs=list(
                    "ggplot2",
                    "ggstatsplot"),
                clearWith=list(
                    "dep",
                    "group",
                    "grvar",
                    "excl",
                    "originaltheme",
                    "typestatistics",
                    "changebinwidth",
                    "binwidth",
                    "barmeasure",
                    "centralityparameter"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="`Histogram Splitted by {grvar}`",
                width=800,
                height=600,
                renderFun=".plot2",
                requiresData=TRUE,
                visible="(grvar)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Histogram",
                renderFun=".plot",
                requiresData=TRUE))}))

jjhistostatsBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jjhistostatsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jjstatsplot',
                name = 'jjhistostats',
                version = c(1,0,0),
                options = options,
                results = jjhistostatsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Histogram
#'
#' 'Wrapper Function for ggstatsplot::gghistostats and
#' ggstatsplot::grouped_gghistostats to generate Histogram.'
#' 
#'
#' @examples
#' \dontrun{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param dep .
#' @param grvar .
#' @param excl .
#' @param typestatistics .
#' @param centralityparameter .
#' @param changebinwidth .
#' @param binwidth .
#' @param barmeasure .
#' @param usexlab .
#' @param xlab .
#' @param useylab .
#' @param ylab .
#' @param usetitle .
#' @param title .
#' @param usesubtitle .
#' @param subtitle .
#' @param useplotcaption .
#' @param plotcaption .
#' @param resultssubtitle .
#' @param originaltheme .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jjhistostats <- function(
    data,
    dep,
    grvar,
    excl = TRUE,
    typestatistics = "parametric",
    centralityparameter = "mean",
    changebinwidth = FALSE,
    binwidth = 1.1,
    barmeasure = "count",
    usexlab = FALSE,
    xlab = "",
    useylab = FALSE,
    ylab = "",
    usetitle = FALSE,
    title = "",
    usesubtitle = FALSE,
    subtitle = "",
    useplotcaption = FALSE,
    plotcaption = "",
    resultssubtitle = TRUE,
    originaltheme = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('jjhistostats requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(grvar)) grvar <- jmvcore::resolveQuo(jmvcore::enquo(grvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(grvar), grvar, NULL))

    for (v in grvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jjhistostatsOptions$new(
        dep = dep,
        grvar = grvar,
        excl = excl,
        typestatistics = typestatistics,
        centralityparameter = centralityparameter,
        changebinwidth = changebinwidth,
        binwidth = binwidth,
        barmeasure = barmeasure,
        usexlab = usexlab,
        xlab = xlab,
        useylab = useylab,
        ylab = ylab,
        usetitle = usetitle,
        title = title,
        usesubtitle = usesubtitle,
        subtitle = subtitle,
        useplotcaption = useplotcaption,
        plotcaption = plotcaption,
        resultssubtitle = resultssubtitle,
        originaltheme = originaltheme)

    analysis <- jjhistostatsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
