# GENERATED by _updateModules tooling: @importFrom tags to satisfy R CMD check
# 'Namespaces in Imports field not imported from' NOTE for pkg::-used packages.
#' @importFrom BayesFactor ttestBF
#' @importFrom boot boot
#' @importFrom car leveneTest
#' @importFrom cowplot plot_grid
#' @importFrom easyalluvial alluvial_wide
#' @importFrom ggalluvial StatStratum
#' @importFrom ggExtra ggMarginal
#' @importFrom ggprism prism_colour_pal
#' @importFrom ggrepel geom_text_repel
#' @importFrom ggsegmentedtotalbar ggsegmentedtotalbar
#' @importFrom haven as_factor
#' @importFrom methods hasArg
#' @importFrom patchwork wrap_plots
#' @importFrom tools toTitleCase
#' @importFrom viridisLite turbo
#' @importFrom withr local_preserve_seed
#' @importFrom WRS2 yuen
#' @importFrom correlation correlation
#' @importFrom ggridges geom_density_ridges stat_density_ridges theme_ridges
#' @importFrom statsExpressions oneway_anova two_sample_test corr_test contingency_table
#' @importFrom waffle geom_waffle
NULL

